services:
  dev:
    init: true
    build:
      context: ./
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/workspaces/workdir
    working_dir: /workspaces/workdir
    command: sleep infinity

# Necessary without "implicit_networking: true":
# networks:
#   default:
#     external: true
#     name: ${IFRIT_SHARED_NETWORK}
